sonar.projectKey=apm-vite
sonar.sources=web/src,electron
sonar.tests=web/src,tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.cy.ts,**/*.cy.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-electron/**,**/out/**,**/release/**,web/src/assets/**,web/src/store/localization/model.tsx,web/src/store/localization/reducers.tsx,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.cy.ts,**/*.cy.tsx
sonar.typescript.tsconfigPaths=tsconfig.web.json,tsconfig.node.json
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
sonar.javascript.node.maxspace=8192
