import { useEffect, useRef, useState } from 'react';
import { Alert, Snackbar } from '@mui/material';
import { shallowEqual, useSelector } from 'react-redux';
import { IMainStrings } from '../model';
import { mainSelector } from '../selector';
import { Button } from '../control';

/**
 * Web-only PWA update prompt.
 *
 * Registers the service worker generated by vite-plugin-pwa and, when a new
 * build has been deployed, shows a persistent "reload to update" snackbar
 * instead of silently taking over the page. This avoids stale-shell / chunk
 * mismatch errors mid-session (see vite.config.ts: skipWaiting/clientsClaim are
 * both false). Mounted only on the web build (see Root.tsx) so it never runs in
 * Electron; the effect also no-ops where service workers are unavailable
 * (e.g. jsdom tests, http contexts without SW support).
 */
export const PwaUpdatePrompt = () => {
  const t: IMainStrings = useSelector(mainSelector, shallowEqual);
  const [needRefresh, setNeedRefresh] = useState(false);
  const updateSW = useRef<((reloadPage?: boolean) => Promise<void>) | null>(
    null
  );

  useEffect(() => {
    if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
      return;
    }
    let cancelled = false;
    import('virtual:pwa-register')
      .then(({ registerSW }) => {
        if (cancelled) return;
        updateSW.current = registerSW({
          onNeedRefresh() {
            setNeedRefresh(true);
          },
        });
      })
      .catch(() => {
        // No service worker in this environment; nothing to prompt.
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const handleReload = () => {
    setNeedRefresh(false);
    updateSW.current?.(true);
  };

  return (
    <Snackbar
      open={needRefresh}
      anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
    >
      <Alert
        severity="info"
        action={
          <Button color="inherit" size="small" onClick={handleReload}>
            {t.pwaReload}
          </Button>
        }
      >
        {t.pwaUpdateReady}
      </Alert>
    </Snackbar>
  );
};

export default PwaUpdatePrompt;
