import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { ThemeProvider } from '@mui/material/styles';
import { createAppTheme } from '../../../theme';
import AddResourceWizard, { WizardLaunch } from './AddResourceWizard';
import { AddResourceAction } from './AddResourceAction';
import usePassageDetailContext from '../../../context/usePassageDetailContext';

const theme = createAppTheme('en');

// --- strings -----------------------------------------------------------------
jest.mock('react-redux', () => ({
  shallowEqual: (a: unknown, b: unknown) => a === b,
  useSelector: () => ({
    addAudioResource: 'Add Audio Resource',
    editGeneralResource: 'Edit General Resource',
    selectPassagesSub: 'Select passages for {0}',
    editingFile: 'You are editing {0}',
    generalResourcesIndividually:
      'General resources should be uploaded individually',
    confirmCloseTitle: 'Confirm Close',
    confirmClose: 'Discard changes?',
    keepOpen: 'Keep Open',
    discardAndClose: 'Discard and Close',
    noteResource: 'Note Resource',
    passageResource: 'Passage Resource',
    bookResource: 'Book Resource',
    movementResource: 'Movement Resource',
    // media-upload title strings (same mock object serves every selector)
    resourceTitle: 'Add Resource',
    linkTitle: 'Add Link',
    markdownTitle: 'Add Text',
    pdfResourceTitle: 'Add PDF Resource',
    faithbridgeTitle: 'Add {0} Resource',
  }),
}));

jest.mock('../../../selector', () => ({
  passageDetailArtifactsSelector: jest.fn(),
  sharedSelector: jest.fn(),
  mediaUploadSelector: jest.fn(),
}));

// --- context / data ----------------------------------------------------------
jest.mock('../../../context/usePassageDetailContext', () => ({
  __esModule: true,
  default: jest.fn(),
}));

const mockArtifactTypes = [
  { id: 'resource-type', attributes: { typename: 'resource' } },
  { id: 'project-resource-type', attributes: { typename: 'projectresource' } },
];
const mockEmpty: unknown[] = [];
jest.mock('../../../hoc/useOrbitData', () => ({
  useOrbitData: (type: string) =>
    type === 'artifacttype' ? mockArtifactTypes : mockEmpty,
}));

jest.mock('../../../context/useGlobal', () => ({
  useGlobal: jest.fn((key: string) => {
    const values: Record<string, unknown> = {
      memory: {
        update: jest.fn(() => Promise.resolve()),
        cache: { query: jest.fn(() => undefined) },
        keyMap: {},
      },
      offlineOnly: false,
      progress: 0,
      plan: '',
    };
    return [values[key], jest.fn()];
  }),
}));

// --- crud / helpers ----------------------------------------------------------
const mockAddSectionResource = jest.fn();
jest.mock('../../../crud', () => ({
  remoteIdGuid: (_t: string, remId: string) => remId,
  useSecResCreate: () => ({
    AddSectionResource: mockAddSectionResource,
    InternalizationStep: jest.fn(() => ({ id: 'step-1' })),
  }),
  related: jest.fn(() => ''),
  useOrganizedBy: () => ({
    getOrganizedBy: (current: boolean) => (current ? 'Section' : 'Project'),
  }),
  findRecord: jest.fn((_m: unknown, _t: string, id: string) => ({
    id,
    type: 'mediafile',
    attributes: { originalFile: 'a.mp3' },
  })),
  usePlan: () => ({ getPlan: jest.fn(() => null) }),
}));

jest.mock('./useProjectResourceSave', () => ({
  useProjectResourceSave: () => jest.fn(),
}));
jest.mock('./useResumePendingProjectResourceConfig', () => ({
  useResumePendingProjectResourceConfig: jest.fn(),
}));

const mockIsVisual = jest.fn((_m?: unknown) => false);
jest.mock('../../../utils', () => ({
  isVisual: (m: unknown) => mockIsVisual(m),
  removeExtension: () => ({ name: 'a' }),
  safeFileBasename: (s?: string) => s ?? '',
}));

jest.mock('./projectResourceAssignments', () => ({
  getProjectResourceAssignments: jest.fn(() => []),
  removeUnselectedProjectResourceAssignments: jest.fn(() => Promise.resolve()),
}));

jest.mock('./resourceArtifactName', () => ({
  descriptionRequiredForResource: jest.fn(() => false),
}));
jest.mock('./buildResourcePendingRestore', () => ({
  buildResourcePendingRestore: jest.fn(() => undefined),
}));
jest.mock('./resourceRows', () => ({ AIGenerated: 'Generated By AI' }));

jest.mock('../../../hoc/SnackBar', () => ({
  useSnackBar: () => ({ showMessage: jest.fn() }),
}));

// --- dialog + step child mocks ----------------------------------------------
jest.mock('../../../hoc/BigDialog', () => ({
  __esModule: true,
  default: ({
    isOpen,
    title,
    description,
    children,
    onOpen,
  }: {
    isOpen?: boolean;
    title?: React.ReactNode;
    description?: React.ReactNode;
    children?: React.ReactNode;
    onOpen?: (open: boolean) => void;
  }) =>
    isOpen ? (
      <div data-testid="post-dialog">
        <div>{title}</div>
        {description}
        {children}
        <button type="button" onClick={() => onOpen?.(false)}>
          dialog-x
        </button>
      </div>
    ) : null,
}));

const file = (name: string) => new File([name], name, { type: 'audio/mpeg' });

jest.mock('../../Uploader', () => {
  const { UploadType } = jest.requireActual('../../UploadType');
  return {
    __esModule: true,
    default: ({
      isOpen,
      uploadType,
      ready,
      validationMessage,
      onFiles,
      onStageFiles,
      finish,
      initialFiles,
      importList,
      metaData,
      onOpen,
    }: {
      isOpen?: boolean;
      uploadType?: unknown;
      ready?: () => boolean;
      validationMessage?: string;
      onFiles?: (f: File[]) => void;
      onStageFiles?: (f: File[], recorded?: boolean) => void;
      finish?: (planId: string, ids: string[]) => void;
      initialFiles?: File[];
      importList?: File[];
      metaData?: React.ReactNode;
      onOpen?: (open: boolean) => void;
    }) => {
      const isProject = uploadType === UploadType.ProjectResource;
      return (
        <>
          {/* The deferred upload runs headlessly while the dialog is closed;
              expose a trigger whenever an importList-driven upload is in flight. */}
          {importList && importList.length > 0 && (
            <button type="button" onClick={() => finish?.('plan', ['media-1'])}>
              finish-import
            </button>
          )}
          {isOpen && (
            <div data-testid="uploader">
              <span>uploader-open</span>
              <span>initial-files:{initialFiles?.length ?? 0}</span>
              {metaData}
              <button
                type="button"
                onClick={() => onFiles?.([file('a'), file('b')])}
              >
                select-two-files
              </button>
              <button type="button" onClick={() => onFiles?.([file('a')])}>
                select-one-file
              </button>
              <button type="button" onClick={() => onStageFiles?.([file('a')])}>
                stage-one-file
              </button>
              <button
                type="button"
                onClick={() => onStageFiles?.([file('a')], /* recorded */ true)}
              >
                stage-one-recording
              </button>
              <button
                type="button"
                onClick={() => finish?.('plan', ['media-1'])}
              >
                finish-upload
              </button>
              {validationMessage && <div>{validationMessage}</div>}
              <button type="button" disabled={!ready?.()}>
                {isProject ? 'Next' : 'Upload'}
              </button>
              <button type="button" onClick={() => onOpen?.(false)}>
                uploader-x
              </button>
            </div>
          )}
        </>
      );
    },
  };
});

jest.mock('./ResourceData', () => {
  const { ResourceTypeEnum } = jest.requireActual('./ResourceTypeEnum');
  return {
    __esModule: true,
    default: ({
      onDescriptionChange,
      onPassResChange,
    }: {
      onDescriptionChange: (d: string) => void;
      onPassResChange?: (k: number) => void;
    }) => (
      <div>
        <button type="button" onClick={() => onDescriptionChange('desc')}>
          set-desc
        </button>
        <button
          type="button"
          onClick={() => onPassResChange?.(ResourceTypeEnum.projectResource)}
        >
          set-general
        </button>
      </div>
    ),
  };
});

jest.mock('./SelectSections', () => ({
  __esModule: true,
  default: ({
    uploadsOnNext,
    uploading,
    onSelect,
    onBack,
  }: {
    uploadsOnNext?: boolean;
    uploading?: boolean;
    onSelect?: (items: unknown[], candidates: unknown[]) => void;
    onBack?: () => void;
  }) => (
    <div data-testid="select-sections">
      <span>SelectSections</span>
      <span>{uploadsOnNext ? 'btn-upload' : 'btn-next'}</span>
      {uploading && <span>uploading</span>}
      <button
        type="button"
        onClick={() =>
          onSelect?.(
            [{ type: 'passage', id: 'p1' }],
            [
              { type: 'passage', id: 'p1' },
              { type: 'section', id: 's1' },
            ]
          )
        }
      >
        sections-select
      </button>
      {onBack && (
        <button type="button" onClick={onBack}>
          sections-back
        </button>
      )}
    </div>
  ),
}));

jest.mock('./ProjectResourceConfigure', () => ({
  __esModule: true,
  default: ({
    onBack,
    onOpen,
  }: {
    onBack?: () => void;
    onOpen?: (open: boolean) => void;
  }) => (
    <div data-testid="configure">
      <span>Configure</span>
      {onBack && (
        <button type="button" onClick={onBack}>
          configure-back
        </button>
      )}
      <button type="button" onClick={() => onOpen?.(false)}>
        configure-done
      </button>
    </div>
  ),
}));

jest.mock('../../AlertDialog', () => ({
  __esModule: true,
  default: ({
    text,
    yes,
    no,
    yesResponse,
    noResponse,
  }: {
    text?: string;
    yes?: string;
    no?: string;
    yesResponse?: () => void;
    noResponse?: () => void;
  }) => (
    <div data-testid="confirm">
      <span>{text}</span>
      <button type="button" onClick={yesResponse}>
        {yes}
      </button>
      <button type="button" onClick={noResponse}>
        {no}
      </button>
    </div>
  ),
}));

const mockContext = usePassageDetailContext as jest.MockedFunction<
  typeof usePassageDetailContext
>;

const renderWizard = (launch: WizardLaunch) =>
  render(
    <ThemeProvider theme={theme}>
      <AddResourceWizard launch={launch} onLaunchHandled={jest.fn()} />
    </ThemeProvider>
  );

// Drive the common add → General → stage path to the section-select step.
const stageToSelectSections = () => {
  fireEvent.click(screen.getByText('set-general'));
  fireEvent.click(screen.getByText('stage-one-file'));
};

// Same, but the staged audio is a recorded take (recorded=true) rather than a
// plain file upload — closing then confirms, since a recording is lost (#719).
const stageRecordingToSelectSections = () => {
  fireEvent.click(screen.getByText('set-general'));
  fireEvent.click(screen.getByText('stage-one-recording'));
};

describe('AddResourceWizard', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockIsVisual.mockReturnValue(false);
    mockContext.mockReturnValue({
      rowData: [],
      section: { id: 'section-1', attributes: { level: 0 } },
      passage: { id: 'passage-1', attributes: { reference: 'GEN 1:1' } },
      currentstep: {} as never,
      setSelected: jest.fn(),
    } as never);
  });

  it('disables Next and shows the validation message for multi-file general uploads', () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    fireEvent.click(screen.getByText('set-general'));
    fireEvent.click(screen.getByText('select-two-files'));

    expect(
      screen.getByText('General resources should be uploaded individually')
    ).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Next' })).toBeDisabled();
  });

  it('titles the single dialog by the upload step type', () => {
    const audio = renderWizard({
      kind: 'add',
      action: AddResourceAction.Audio,
    });
    expect(screen.getByText('Add Audio Resource')).toBeInTheDocument();
    audio.unmount();

    const pdf = renderWizard({ kind: 'add', action: AddResourceAction.Pdf });
    expect(screen.getByText('Add PDF Resource')).toBeInTheDocument();
    pdf.unmount();

    renderWizard({ kind: 'add', action: AddResourceAction.Link });
    expect(screen.getByText('Add Link')).toBeInTheDocument();
  });

  it('advances from upload to the section-select step when a single general file is staged', () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    stageToSelectSections();

    expect(screen.getByTestId('select-sections')).toBeInTheDocument();
    // Fresh add with no media yet: the button uploads.
    expect(screen.getByText('btn-upload')).toBeInTheDocument();
  });

  it('preserves the staged file when going Back from section-select to upload', () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    stageToSelectSections();

    fireEvent.click(screen.getByText('sections-back'));

    expect(screen.getByText('uploader-open')).toBeInTheDocument();
    // The previously staged file is handed back as initialFiles.
    expect(screen.getByText('initial-files:1')).toBeInTheDocument();
  });

  it('keeps SelectSections mounted while on the configure step (Back preserves it)', async () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    stageToSelectSections();

    // Choose sections → deferred upload fires → configure step.
    fireEvent.click(screen.getByText('sections-select'));
    fireEvent.click(screen.getByText('finish-import'));

    await waitFor(() =>
      expect(screen.getByTestId('configure')).toBeInTheDocument()
    );
    // SelectSections stays mounted (CSS-hidden) under the same dialog so its
    // selection survives Back with no re-seeding.
    expect(screen.getByTestId('select-sections')).toBeInTheDocument();

    fireEvent.click(screen.getByText('configure-back'));
    expect(screen.queryByTestId('configure')).not.toBeInTheDocument();
    expect(screen.getByTestId('select-sections')).toBeInTheDocument();
  });

  it('opens an existing general resource at section-select with no upload, advancing straight to configure', () => {
    renderWizard({
      kind: 'editGeneral',
      media: {
        id: 'm1',
        type: 'mediafile',
        attributes: { originalFile: 'f.mp3' },
      } as never,
    });

    expect(screen.getByTestId('select-sections')).toBeInTheDocument();
    // Media already exists: the button advances rather than uploads, and there
    // is no Back (no previous upload step).
    expect(screen.getByText('btn-next')).toBeInTheDocument();
    expect(screen.queryByText('sections-back')).not.toBeInTheDocument();

    fireEvent.click(screen.getByText('sections-select'));
    expect(screen.getByTestId('configure')).toBeInTheDocument();
    // No upload happened.
    expect(screen.queryByText('finish-import')).not.toBeInTheDocument();
  });

  it('writes a visual resource directly and skips the configure step', async () => {
    mockIsVisual.mockReturnValue(true);
    renderWizard({
      kind: 'editGeneral',
      media: {
        id: 'm1',
        type: 'mediafile',
        attributes: { originalFile: 'f.png' },
      } as never,
    });

    fireEvent.click(screen.getByText('sections-select'));

    await waitFor(() =>
      expect(screen.queryByTestId('post-dialog')).not.toBeInTheDocument()
    );
    expect(screen.queryByTestId('configure')).not.toBeInTheDocument();
  });

  it('closes the section-select step via the X after a discard confirm when a recording was staged', () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    stageRecordingToSelectSections();

    fireEvent.click(screen.getByText('dialog-x'));
    expect(screen.getByTestId('confirm')).toBeInTheDocument();

    fireEvent.click(screen.getByText('Discard and Close'));
    expect(screen.queryByTestId('select-sections')).not.toBeInTheDocument();
    expect(screen.queryByTestId('post-dialog')).not.toBeInTheDocument();
  });

  it('closes the section-select step via the X without confirming when only a file was staged (#719)', () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    stageToSelectSections();

    fireEvent.click(screen.getByText('dialog-x'));
    // A staged file upload is cheap to redo, so closing it does not prompt.
    expect(screen.queryByTestId('confirm')).not.toBeInTheDocument();
    expect(screen.queryByTestId('select-sections')).not.toBeInTheDocument();
    expect(screen.queryByTestId('post-dialog')).not.toBeInTheDocument();
  });

  it('closes the wizard after a terminal (section-resource) upload', async () => {
    renderWizard({ kind: 'add', action: AddResourceAction.Audio });
    // No General toggle: a plain section resource.
    fireEvent.click(screen.getByText('finish-upload'));

    await waitFor(() =>
      expect(screen.queryByText('uploader-open')).not.toBeInTheDocument()
    );
    expect(mockAddSectionResource).toHaveBeenCalled();
  });
});
