import {
  ArtifactCategory,
  ArtifactType,
  MediaFileD,
  SectionResourceD,
  SectionResourceUser,
} from '../../../model';
import { related, VernacularTag } from '../../../crud';
import { IRow } from '../../../context/PassageDetailContext';
import { isVisual } from '../../../utils';
import { mediaContentType } from '../../../utils/contentType';
import { resourceArtifactName } from './resourceArtifactName';
import {
  generalResourceMedia,
  projectResourceTypeIds,
} from './generalResourceMedia';
import { ArtifactTypeSlug } from '../../../crud/artifactTypeSlug';

/**
 * Label key for shared resources. Not an {@link ArtifactTypeSlug}: no artifact
 * type is stored under this name, it only names the `artifactType.linked`
 * string.
 */
const LinkedTypeSlug = 'linked';

const isResource = (typeSlug: string) =>
  ['resource', 'sharedresource', 'airesource'].indexOf(typeSlug) !== -1;

interface DataProps {
  artifactTypes: ArtifactType[];
  categories: ArtifactCategory[];
  userResources: SectionResourceUser[];
  user: string;
  localizedCategory: (slug: string) => string;
  localizedType: (slug: string) => string;
}

interface RowProps extends DataProps {
  newRow: IRow[];
  r: SectionResourceD | null;
  media: MediaFileD | undefined;
  sourceversion: number;
  /** All media, so a derived copy can be traced back to its general resource. */
  mediafiles?: MediaFileD[];
}
export const AIGenerated = 'Generated By AI';

export const oneMediaRow = ({
  newRow,
  r,
  media,
  sourceversion,
  artifactTypes,
  categories,
  userResources,
  user,
  localizedCategory,
  localizedType,
  mediafiles = [],
}: RowProps) => {
  const mediaAttr = media?.attributes;
  const typId = related(media, 'artifactType');
  const artifactType = artifactTypes.find((t) => t.id === typId);
  let typeNameSlug = artifactType?.attributes?.typename || '';
  if (
    typeNameSlug === 'resource' &&
    media?.attributes.eafUrl?.includes(AIGenerated)
  )
    typeNameSlug = 'airesource';
  // Derived copies of a general resource carry the plain `resource` type, so
  // the general-resource label comes from the same source-media resolution the
  // Edit action uses (see [[generalResourceMedia]]).
  //
  // The row's own type is checked too: back translations, consultant checks and
  // offline copies also point at their source through `sourceMedia` (see
  // derivedResourceMedia in projectResourceAssignments), and those are not
  // general resources even when that source happens to be one.
  const isGeneralResource =
    (typeNameSlug === ArtifactTypeSlug.Resource ||
      typeNameSlug === ArtifactTypeSlug.ProjectResource) &&
    Boolean(
      generalResourceMedia(
        media,
        mediafiles,
        projectResourceTypeIds(artifactTypes)
      )
    );
  // Label key, which is not always the media's own type: a derived copy reads
  // as its general-resource root, and `sharedresource` reads as "Linked". The
  // latter is its own string rather than a reworded `artifactType.sharedresource`
  // so the existing translations of "Shared Resource" stay correct wherever that
  // key is still shown.
  const displayTypeSlug = isGeneralResource
    ? ArtifactTypeSlug.ProjectResource
    : typeNameSlug === ArtifactTypeSlug.SharedResource
      ? LinkedTypeSlug
      : typeNameSlug;
  const catId = related(media, 'artifactCategory');
  const category = categories.find((c) => c.id === catId);
  const catNameSlug = category?.attributes?.categoryname || '';
  const done = Boolean(
    r &&
    userResources.find(
      (u) =>
        related(u, 'sectionresource') === r.id && related(u, 'user') === user
    )
  );
  newRow.push({
    id: media?.id || '',
    playItem: '',
    sequenceNum: r?.attributes.sequenceNum || 0,
    version: mediaAttr?.versionNumber || 0,
    artifactName: resourceArtifactName(
      r?.attributes.description,
      mediaAttr?.originalFile,
      mediaContentType(media)
    ),
    artifactType: localizedType(displayTypeSlug),
    artifactTypeSlug: typeNameSlug,
    isGeneralResource,
    artifactCategory: localizedCategory(catNameSlug),
    done,
    editAction: null,
    mediafile: media || ({} as MediaFileD),
    resource: r,
    isResource: isResource(typeNameSlug),
    passageId: (r ? related(r, 'passage') : related(media, 'passage')) || '',
    isComment: typeNameSlug === 'comment',
    isKeyTerm: typeNameSlug === 'keyterm',
    isVernacular: typeNameSlug === '' || typeNameSlug === 'vernacular',
    isText: isVisual(media),
    sourceVersion: sourceversion,
  });
  return newRow;
};

interface MediaProps extends DataProps {
  mediafiles: MediaFileD[];
}

export const mediaRows = (props: MediaProps) => {
  const { mediafiles, artifactTypes } = props;

  const newRow = new Array<IRow>();
  // sort takes the greatest version but if they're equal, keeps the
  // one loaded first which is the vernacular media
  mediafiles
    .filter((m) => m?.attributes?.versionNumber !== undefined)
    .sort((i, j) => {
      const iType = related(i, 'artifactType');
      const jType = related(j, 'artifactType');
      const icmt = iType !== VernacularTag;
      const jcmt = jType !== VernacularTag;
      return !icmt && jcmt
        ? -1
        : icmt && !jcmt
          ? 1
          : j.attributes.versionNumber - i.attributes.versionNumber;
    })
    .forEach((media) => {
      const typId = related(media, 'artifactType');
      const artifactType = artifactTypes.find((t) => t.id === typId);
      const typeNameSlug = artifactType?.attributes?.typename || '';
      let sourceversion = 0;
      const relatedMedia = related(media, 'sourceMedia');
      if (relatedMedia) {
        const m = mediafiles.find((m) => m.id === relatedMedia);
        sourceversion = m?.attributes?.versionNumber || 0;
      }
      if (!isResource(typeNameSlug))
        oneMediaRow({ ...props, newRow, r: null, media, sourceversion });
    });
  return newRow;
};

interface IProps extends DataProps {
  res: SectionResourceD[];
  mediafiles: MediaFileD[];
}

export const resourceRows = (props: IProps) => {
  const { res, mediafiles } = props;
  const newRow = Array<IRow>();
  res.forEach((r) => {
    const id = related(r, 'mediafile');
    const media = mediafiles.find((m) => m.id === id);
    oneMediaRow({ ...props, newRow, r, media, sourceversion: 0 });
  });
  return newRow;
};
